export const CREATE_PLAYER = "CREATE_PLAYER";
export const RETRIEVE_PLAYERS = "RETRIEVE_PLAYERS";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const DELETE_ALL_PLAYERS = "DELETE_ALL_PLAYERS";